"""utenti, biblioteca, stanze

Revisione: 7dbb0c954bd3
Precedente: 
Creata: 2026-09-22 15:32:07.408606

Una migrazione si legge come una frase: cosa cambia, e come si torna indietro.
Se `giu()` resta vuota, quella migrazione non si puo' annullare - va detto qui
sopra, non scoperto la sera che serve.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '7dbb0c954bd3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utenti',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('ANONIMO', 'REGISTRATO', name='tipo_utente'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nome', sa.String(length=40), nullable=True),
    sa.Column('nome_visibile', sa.String(length=40), nullable=False),
    sa.Column('creato', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('visto', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('bloccato', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_utenti_potatura', 'utenti', ['tipo', 'visto'], unique=False)
    op.create_index(op.f('ix_utenti_tipo'), 'utenti', ['tipo'], unique=False)
    op.create_table('biblioteca',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utente_id', sa.UUID(), nullable=False),
    sa.Column('genere', sa.Enum('CRONOLOGIA', 'PREFERITO', 'FONTE', 'GRUPPO', name='genere_voce'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('titolo', sa.String(length=300), nullable=False),
    sa.Column('titolo_tuo', sa.Boolean(), nullable=False),
    sa.Column('piattaforma', sa.String(length=40), nullable=False),
    sa.Column('posizione', sa.Float(), nullable=True),
    sa.Column('durata', sa.Float(), nullable=True),
    sa.Column('dati', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creata', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aggiornata', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_biblioteca_link', 'biblioteca', ['utente_id', 'genere', 'url'], unique=True)
    op.create_index('ix_biblioteca_mia', 'biblioteca', ['utente_id', 'genere', 'aggiornata'], unique=False)
    op.create_table('stanze',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codice', sa.String(length=48), nullable=False),
    sa.Column('titolo', sa.String(length=80), nullable=False),
    sa.Column('padrone_id', sa.UUID(), nullable=False),
    sa.Column('visibilita', sa.Enum('PUBBLICA', 'NON_IN_ELENCO', 'PRIVATA', name='visibilita_stanza'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('url_corrente', sa.Text(), nullable=True),
    sa.Column('titolo_corrente', sa.String(length=200), nullable=True),
    sa.Column('aperta', sa.Boolean(), nullable=False),
    sa.Column('max_persone', sa.Integer(), nullable=False),
    sa.Column('creata', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultima_attivita', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['padrone_id'], ['utenti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice')
    )
    op.create_index(op.f('ix_stanze_padrone_id'), 'stanze', ['padrone_id'], unique=False)
    op.create_index('ix_stanze_ricerca', 'stanze', ['visibilita', 'aperta', 'ultima_attivita'], unique=False)
    op.create_table('membri_stanza',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stanza_id', sa.UUID(), nullable=False),
    sa.Column('utente_id', sa.UUID(), nullable=False),
    sa.Column('ruolo', sa.Enum('PADRONE', 'PRESENTATORE', 'OSPITE', name='ruolo_stanza'), nullable=False),
    sa.Column('entrato', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stanza_id'], ['stanze.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_membri_unici', 'membri_stanza', ['stanza_id', 'utente_id'], unique=True)
    op.create_table('messaggi_stanza',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stanza_id', sa.UUID(), nullable=False),
    sa.Column('autore_id', sa.UUID(), nullable=True),
    sa.Column('autore_nome', sa.String(length=40), nullable=False),
    sa.Column('testo', sa.String(length=800), nullable=False),
    sa.Column('quando', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autore_id'], ['utenti.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stanza_id'], ['stanze.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messaggi_stanza_tempo', 'messaggi_stanza', ['stanza_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messaggi_stanza_tempo', table_name='messaggi_stanza')
    op.drop_table('messaggi_stanza')
    op.drop_index('ix_membri_unici', table_name='membri_stanza')
    op.drop_table('membri_stanza')
    op.drop_index('ix_stanze_ricerca', table_name='stanze')
    op.drop_index(op.f('ix_stanze_padrone_id'), table_name='stanze')
    op.drop_table('stanze')
    op.drop_index('ix_biblioteca_mia', table_name='biblioteca')
    op.drop_index('ix_biblioteca_link', table_name='biblioteca')
    op.drop_table('biblioteca')
    op.drop_index(op.f('ix_utenti_tipo'), table_name='utenti')
    op.drop_index('ix_utenti_potatura', table_name='utenti')
    op.drop_table('utenti')
    # ### end Alembic commands ###
