"""lingua scelta sull'utente

Revisione: b15ebc1f4eb3
Precedente: 7dbb0c954bd3
Creata: 2026-09-22 16:14:45.170694

Una migrazione si legge come una frase: cosa cambia, e come si torna indietro.
Se `giu()` resta vuota, quella migrazione non si puo' annullare - va detto qui
sopra, non scoperto la sera che serve.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b15ebc1f4eb3'
down_revision: str | None = '7dbb0c954bd3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utenti', sa.Column('lingua', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utenti', 'lingua')
    # ### end Alembic commands ###
